import Pet1 from "/img/pets/1.png";
import Pet2 from "/img/pets/2.png";
import Pet3 from "/img/pets/3.png";
import Pet4 from "/img/pets/4.png";
import Pet5 from "/img/pets/5.png";
import Pet6 from "/img/pets/6.png";
import Pet7 from "/img/pets/7.png";
import Pet8 from "/img/pets/8.png";
import Pet9 from "/img/pets/9.png";
import Pet10 from "/img/pets/10.png";
import Pet11 from "/img/pets/11.png";
import Pet12 from "/img/pets/12.png";

const pets = [
  {
    id: 1,
    type: "cat",
    name: "koki",
    petImage: Pet1,
    colour: "red",
    gender: "male",
    breed: "koki",
    birthdate: "27/09/2001",
    age: 5,
  },
  {
    id: 2,
    type: "bird",
    name: "chirpy",
    breed: "koki",
    petImage: Pet2,
    colour: "red",
    gender: "male",
    breed: "koki",
    birthdate: "27/09/2001",
    age: 5,
  },
  {
    id: 3,
    type: "fox",
    name: "froxy",
    petImage: Pet3,
    colour: "red",
    gender: "male",
    breed: "koki",
    birthdate: "27/09/2001",
    age: 5,
  },
  {
    id: 4,
    type: "cat",
    name: "kristy",
    petImage: Pet4,
    colour: "red",
    gender: "male",
    breed: "koki",
    birthdate: "27/09/2001",
    age: 5,
  },
  {
    id: 5,
    type: "hamster",
    name: "molu",
    petImage: Pet5,
    colour: "red",
    gender: "male",
    breed: "koki",
    birthdate: "27/09/2001",
    age: 5,
  },
  {
    id: 6,
    type: "parrot",
    name: "pelu",
    petImage: Pet6,
    colour: "red",
    gender: "male",
    breed: "koki",
    birthdate: "27/09/2001",
    age: 5,
  },
  {
    id: 7,
    type: "parrot",
    name: "pomo",
    petImage: Pet7,
    colour: "red",
    gender: "male",
    breed: "koki",
    birthdate: "27/09/2001",
    age: 5,
  },
  {
    id: 8,
    type: "cat",
    name: "yoshi",
    petImage: Pet8,
    colour: "red",
    gender: "male",
    breed: "koki",
    birthdate: "27/09/2001",
    age: 5,
  },
  {
    id: 9,
    type: "lion",
    name: "musa",
    petImage: Pet9,
    colour: "red",
    gender: "male",
    breed: "koki",
    birthdate: "27/09/2001",
    age: 5,
  },
  {
    id: 10,
    type: "bird",
    name: "dunki",
    petImage: Pet10,
    colour: "red",
    gender: "male",
    breed: "koki",
    birthdate: "27/09/2001",
    age: 5,
  },
  {
    id: 11,
    type: "dog",
    name: "jossy",
    petImage: Pet11,
    colour: "red",
    gender: "male",
    breed: "koki",
    birthdate: "27/09/2001",
    age: 5,
  },
  {
    id: 12,
    type: "hamster",
    name: "hammy",
    petImage: Pet12,
    colour: "red",
    gender: "male",
    breed: "koki",
    birthdate: "27/09/2001",
    age: 5,
  },
];

export default pets;
